### ISSUE TITLE
The box image not loading in the web

### ISSUE THREAD

**Issue by vi241** [VerdantGameOfficial/issues#10]
**The box image not loading in the web**
Self explanatory

<img width="738" alt="Screen Shot 2022-05-11 at 8 24 47" src="https://user-images.githubusercontent.com/60016719/167775035-3fdcdb79-1bab-453f-af79-a6227b29210d.png">

**Comment by vi241** [comment]
might be intentional, probably not idk

**Comment by Just-a-Unity-Dev** [comment]
Already fixed + duplicate issue
