### ISSUE TITLE
Verdant.app is damaged

### ISSUE THREAD

**Issue by vi241** [VerdantGameOfficial/issues#11]
On macos after I downloaded the app from itch.io it doesnt run because the app is "damaged". I just extracted it from the zip file.
<img width="275" alt="Screen Shot 2022-05-11 at 8 32 22" src="https://user-images.githubusercontent.com/60016719/167775970-3e8652db-b7e6-4018-99ea-65fee07c2a14.png">

**Comment by Just-a-Unity-Dev** [comment]
Refer to this StackExchange post

https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t

**Comment by vi241** [comment]
Not on Catalina and on M1, that
might be the problem
