### ISSUE TITLE
enemy murder paradox

### ISSUE THREAD

**Issue by cinderthein** [VerdantGameOfficial/issues#15]
if an enemy kills another enemy, it doesn't say you killed it, it says the enemy killed it. however, the game only counts enemies you killed as beeing dead, meaning you can't progress through altar

**Comment by ZakChrom** [comment]
oh so thats why didnt progress to level 8 even tho there wasnt any enemies left

**Comment by Just-a-Unity-Dev** [comment]
Please follow the bug report template, closed, reopen using the template
