### ISSUE TITLE
I am once again asking for sky area

### ISSUE THREAD

**Issue by cinderthein** [VerdantGameOfficial/issues#17]
https://discord.com/channels/928809851465904179/973676745163145266

do it. add the thing.

**Comment by cinderthein** [comment]
DO IT

ADD THE FUCKING THING

**Comment by Just-a-Unity-Dev** [comment]
technically the entire map is a sky area sooool

**Comment by cinderthein** [comment]
fine, where connor

**Comment by cinderthein** [comment]
if no connor present then add the sky area I suggested

**Comment by Just-a-Unity-Dev** [comment]
considered
