### ISSUE TITLE
Bug: After the fifth wave, sometimes robots do not spawn

### ISSUE THREAD

**Issue by Aflyde** [VerdantGameOfficial/issues#18]
**Describe the bug**
As the title sais

**Screenshots**
![image](https://user-images.githubusercontent.com/105006958/168326152-24bae7f8-2e13-4f2e-bd93-bdcad11e9b7d.png)
![image](https://user-images.githubusercontent.com/105006958/168329354-3393f3f7-62b0-4874-adb6-5a7cf776e91e.png)
![image](https://user-images.githubusercontent.com/105006958/168329420-ae752b8c-462a-4a73-be78-754b6a61d4ab.png)

**Desktop**
 - OS: Windows 11

**Comment by Just-a-Unity-Dev** [comment]
![Screenshot_2022-05-17-01-52-58-26_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/67359748/168653353-5529311c-1f65-43a2-99eb-7d557fa196b3.jpg)

Not stale, a user found the cause
