### ISSUE TITLE
a speed bug and a texture problem

### ISSUE THREAD

**Issue by sloths2007** [VerdantGameOfficial/issues#2]
sometimes, all your speed just randomly stops, and also a cloud texture has a missing pixel.
![image](https://user-images.githubusercontent.com/105306636/167676588-8ba89153-b288-4f45-a3b1-c70281641bf1.png)
(also you lose all your speed on slopes no matter how fast you are going (also also speed is a bit to fast))

edit: turns out the speed glitch is because there is a random collision in the first level

**Comment by Just-a-Unity-Dev** [comment]
duplicate issue of #5 , cloud wont be fixed
