### ISSUE TITLE
Ability to have grappling hook in the main world

### ISSUE THREAD

**Issue by ZakChrom** [VerdantGameOfficial/issues#21]
### Describe the content or mechanics you want changed/added/removed

Ability to have grappling hook in the main world with the cmd `worldset Player hookUnlocked %b:true` and/or when you beat level 10 in altar dimension thing

### Describe how you think this content will improve the game. If you're proposing new content, mention how it may add more gameplay options or how it will fill a new niche.

It would be cool to have the grappling hook in the main world

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [x] I have read [README.md](https://github.com/VerdantGameOfficial/issues/blob/main/README.md#things-i-wont-add) to make sure my idea is not listed under the "things I wont add" category.

**Comment by Just-a-Unity-Dev** [comment]
Added in 0.4
