### ISSUE TITLE
Bug: Grey screen

### ISSUE THREAD

**Issue by CauseYNot** [VerdantGameOfficial/issues#22]
### What platform are you seeing this bug on?

MacOS

### The exact version number you downloaded the game from. DO NOT PUT LATEST.

Alpha 0.3

### Describe the bug you are having, please include screenshots of the bug

after the altar enemies disappeared i exited and a grey screen occured. Just black

### Describe the steps on how to reproduce the bug.

Just go to altar, wait till enemies stop then exit

### Before making this issue, check the boxes below to confirm that you have acknowledged them.

- [X] I have read [README.md](https://github.com/VerdantGameOfficial/issues/blob/main/README.md#things-i-wont-add) to make sure my idea is not listed under the "things I wont add" category.

**Comment by CauseYNot** [comment]
yeah idk why it happened im sorry e-cripple

**Comment by Just-a-Unity-Dev** [comment]
send screenshots of the bug, and send all crash logs in `~/Library/Application Support/.verdant/`

**Comment by Just-a-Unity-Dev** [comment]
Bump, again please send the logs in `~/Library/Application Support/.verdant/`
